### ISSUE TITLE
BOT IS NOT WORKING

### ISSUE THREAD

**Issue by YogeshVG-1** [tommyryan2002/Ruka-Bot#1]
#
![Screenshot_20210814-023615_Discord](https://user-images.githubusercontent.com/88767337/129424414-cfc9e318-8715-4036-8eef-7da008c02922.jpg)

**Comment by tommyryan2002** [comment]
Are you Direct messaging the bot, or are these commands being typed into a server channel? If the later, what is the server name?

**Comment by YogeshVG-1** [comment]
The commands are being typed in my personal server. The name of the server is 'Akatsuki'.

**Comment by tommyryan2002** [comment]
Ok that server is not coming up in the mongoDB database, so I think the most likely reason is that you added the bot to your server during the brief period that I had to take it offline. Try kicking the bot from your server and re-adding it, and then trying to track the manga. Let me know if that still doesn't work.

**Comment by YogeshVG-1** [comment]
I tried kicking out the bot and inviting it again, the bot still didnt show the manga list  . I Created a new Server and added the bot, that too doesn't seem to work.

**Comment by tommyryan2002** [comment]
I just found the issue, it had to do with some overlapping ID names within the database preventing any new servers from being added. I appreciate you letting me know about the issue! I will have a fix up within the next hour.

**Comment by YogeshVG-1** [comment]
Thanks

**Comment by tommyryan2002** [comment]
Fix is online, go ahead and kick the bot from either server. readding should restore functionality! As always lmk if it still isnt working for some reason.
